openapi: 3.0.3
info:
  description: |
    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
  title: Synctera API
  version: 0.5.0
servers:
- description: Production
  url: https://api.synctera.com/v0
- description: Sandbox (no real world financial impact)
  url: https://api-sandbox.synctera.com/v0
security:
- bearerAuth: []
tags:
- description: Requests to create and manage customers
  name: Customers
paths:
  /customers/prospect:
    post:
      description: |
        Creates a prospect and returns an unique identifier. Use this ID to track disclosures displayed during the KYC flow.  The prospect can be upgraded to a `customer` by updated `customer` resource with collected information.
      operationId: createProspect
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectResponse'
          description: Prospect/Customer id
          links:
            createCustomer:
              description: |
                The `id` value returned in the response can be used as the `id` parameter when creating or getting a customer
              operationId: createCustomer
              parameters:
                id: $response.body#/id
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Create a Prospect
      tags:
      - Customers
    summary: Prospect
  /customers:
    description: |
      The Customer object represents your customer's identity.  You can then verify the identity of this customer and associate them with other people and accounts
    get:
      description: Retrieves paginated list of Customers associated with the authorized
        requester
      operationId: listCustomers
      parameters:
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          description: Maximum of objects to return per page
          example: 100
          minimum: 1
          type: integer
        style: form
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          description: Optional pagination token to be provided to retrieve subsequent
            pages, returned from previous get
          example: faker.random.alphaNumeric(10)
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    customers:
                      description: Array of Customers
                      items:
                        $ref: '#/components/schemas/customer'
                      type: array
                  type: object
                - $ref: '#/components/schemas/paginated_response'
          description: List of customers
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: List Customers
      tags:
      - Customers
    post:
      description: |
        The customer object represents your customer's identity. You can then verify the identity of this customer and associate them with other people and accounts
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
        description: Customer to create
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'
          description: Created customer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource already exists error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Create a Customer
      tags:
      - Customers
    summary: Customer
  /customers/{customer_id}:
    description: |
      This resource represents a customer.  Each customer is identified by an `ID`
    get:
      description: Get Customer based on ID
      operationId: getCustomer
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'
          description: Customer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Get Customer
      tags:
      - Customers
    patch:
      operationId: patchCustomer
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
        description: Customer to be patched
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'
          description: Patched customer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Patch Customer
      tags:
      - Customers
    put:
      operationId: updateCustomer
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
        description: Customer to be updated
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'
          description: Updated customer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Update Customer
      tags:
      - Customers
    summary: Customer
  /customers/{customer_id}/accounts:
    get:
      description: Get paginated list of Accounts associated with user
      operationId: listCustomerAccounts
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          description: Maximum of objects to return per page
          example: 100
          minimum: 1
          type: integer
        style: form
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          description: Optional pagination token to be provided to retrieve subsequent
            pages, returned from previous get
          example: faker.random.alphaNumeric(10)
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    accounts:
                      description: Array of Accounts
                      items:
                        $ref: '#/components/schemas/account'
                      type: array
                  type: object
                - $ref: '#/components/schemas/paginated_response'
          description: List of accounts
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: List accounts
      tags:
      - Customers
    summary: Customer Accounts
  /customers/{customer_id}/accounts/{account_id}:
    get:
      description: Get a specific customer account
      operationId: getCustomerAccount
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: Account ID
        explode: false
        in: path
        name: account_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
          description: Account
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Get customer account
      tags:
      - Customers
    summary: Customer Accounts
components:
  parameters:
    limit:
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 100
        description: Maximum of objects to return per page
        example: 100
        minimum: 1
        type: integer
      style: form
    page_token:
      explode: true
      in: query
      name: page_token
      required: false
      schema:
        description: Optional pagination token to be provided to retrieve subsequent
          pages, returned from previous get
        example: faker.random.alphaNumeric(10)
        type: string
      style: form
    customer_id:
      description: Customer ID
      explode: false
      in: path
      name: customer_id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
    account_id:
      description: Account ID
      explode: false
      in: path
      name: account_id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
  responses:
    unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unauthorized
    forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Forbidden error
    internal_server_error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Internal server error
    bad_request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: BadRequest
    already_exists:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Resource already exists error
    not_found:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Resource not found
  schemas:
    error:
      properties:
        error_details:
          description: Detailed description of error
          example: faker.lorem.sentence
          type: string
      title: Error
      type: object
    address:
      example:
        country_code: faker.address.countryCode
        city: faker.address.city
        address_line_1: faker.address.streetAddress
        default_address_flg: true
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        address_line_2: faker.address.secondaryAddress
        state: faker.address.stateAbbr
        type: work
        postal_code: faker.address.zipCode(#####)
      properties:
        id:
          description: Address unique identifier
          format: uuid
          readOnly: true
          type: string
        default_address_flg:
          description: Denotes whether this address is the person's default address
          type: boolean
        type:
          description: type of address
          enum:
          - home
          - work
          - temporary
          - vacation
          example: work
          type: string
        address_line_1:
          description: Street address line 1
          example: faker.address.streetAddress
          type: string
        address_line_2:
          description: String address line 2
          example: faker.address.secondaryAddress
          type: string
        city:
          description: City
          example: faker.address.city
          type: string
        state:
          description: State, region, province, or prefecture
          example: faker.address.stateAbbr
          type: string
        postal_code:
          description: Postal code
          example: faker.address.zipCode(#####)
          type: string
        country_code:
          description: ISO-3166-1 Alpha-2 country code
          example: faker.address.countryCode
          type: string
      required:
      - address_line_1
      - city
      - country_code
      - default_address_flg
      - postal_code
      - state
      - type
      type: object
    device:
      example:
        screen_width: 0
        screen_height: 6
        os: Android
        ip: faker.internet.ip
        os_version: faker.helpers.replaceSymbols(##.##.##)
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: Resource ID for device
          format: uuid
          type: string
        ip:
          description: IP address
          example: faker.internet.ip
          type: string
        os:
          description: Operation system
          example: Android
          type: string
        os_version:
          description: Operation system version
          example: faker.helpers.replaceSymbols(##.##.##)
          type: string
        screen_width:
          description: Device screen width
          type: integer
        screen_height:
          description: Device screen height
          type: integer
      type: object
    relationship_role:
      description: CUSTODIAN - Related party is the custodian e.g. the parent, BENEFICIARY
        - Related party is the beneficiary e.g. the dependent, PARTNER - Related party
        is the partner
      enum:
      - CUSTODIAN
      - BENEFICIARY
      - PARTNER
      example: CUSTODIAN
      title: Relationship Role
      type: string
    relationship:
      example:
        relationship_role: CUSTODIAN
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: ID of related entity
          format: uuid
          type: string
        relationship_role:
          $ref: '#/components/schemas/relationship_role'
      title: Relationship
      type: object
    status:
      description: |
        The status of the account. Mandatory for shadow mode, optional for lead mode.
      enum:
      - APPLICATION_SUBMITTED
      - FAILED_KYC
      - ACCOUNT_NOT_DESIRED
      - ACTIVE_OR_DISBURSED
      - CLOSED
      - SUSPENDED
      - CHARGED_OFF
      - ACCOUNT_NEVER_ACTIVE
      - ACTIVATED_NOT_DISBURSED
      - AWAITING_FIXING
      - IN_CLOSING
      title: Account Status
      type: string
    schemas-relationship:
      properties:
        connect_id:
          description: Connection ID of the account
          format: uuid
          type: string
        relationship_type:
          description: Relationship type
          enum:
          - ACCOUNT_HOLDER
          - EMPLOYEE
          - BRANCH
          - ATM
          - OFFICER
          - PRIMARY_ACCOUNT_HOLDER
          - JOINT_ACCOUNT_HOLDER
          - AUTHORIZED-SIGNER
          type: string
        customer_id:
          description: Customer that the current account is associated with
          format: uuid
          type: string
      title: Account Relationship
      type: object
    alias:
      properties:
        connect_id:
          description: Connection ID of the account
          format: uuid
          type: string
        id:
          description: Alias ID
          format: uuid
          type: string
        alias_type:
          description: Alias type
          type: string
        alias_name:
          description: Alias name
          type: string
        alias_source:
          description: Alias
          type: string
        alias_info:
          description: Additional information for the alias
          format: byte
          type: string
      title: Account Alias
      type: object
    balance_type:
      description: The type of the balance. GET operation default is for all types
      enum:
      - AVAILABLE_BALANCE
      - ACH
      - MARQETA
      - MASTERCARD
      - PULSE
      type: string
    dc_sign_type:
      description: Indication of debit or credit
      enum:
      - DEBIT
      - CREDIT
      type: string
    balance:
      properties:
        id:
          description: Account ID
          format: uuid
          readOnly: true
          type: string
        posting_date:
          description: Balance at the posting date
          format: date-time
          readOnly: true
          type: string
        balance_type:
          $ref: '#/components/schemas/balance_type'
        currency:
          description: Currency of the balance. ISO 4217 alphabetic currency code
          example: faker.finance.currencyCode
          readOnly: true
          type: string
        amount:
          description: amount in ISO 4217 minor currency units
          minimum: 0
          readOnly: true
          type: integer
        dc_sign:
          $ref: '#/components/schemas/dc_sign_type'
      title: Account balance
      type: object
    transaction:
      properties:
        id:
          description: Transaction ID
          format: uuid
          type: string
        account_id:
          description: Account ID
          format: uuid
          type: string
        currency:
          description: Currency of the transaction. ISO 4217 alphabetic currency code
          example: faker.finance.currencyCode
          type: string
        amount:
          description: Transaction amount in ISO 4217 minor currency units
          minimum: 0
          type: integer
        dc_sign:
          $ref: '#/components/schemas/dc_sign_type'
        effective_date:
          description: The effective date of the transaction (value_date)
          format: date-time
          type: string
        profit_center:
          description: Profit center of the transaction
          type: string
        authorization_ref:
          description: Reference for the authorization
          type: string
        ext_reference:
          description: External reference from Synctera for the transaction
          type: string
        status:
          description: The status of the transaction
          type: string
        transaction_type:
          description: Transaction type
          enum:
          - ACCOUNT_CLOSING_ACH
          - ATM_DEPOSIT_CARD
          - ATM_FEE_CARD
          - ATM_WITHDRAWAL_CARD
          - BALANCE_INQUIRY_CARD
          - CARD_LOAD_CARD
          - CASH_ADVANCE_CARD
          - CHARGEBACK_CARD
          - CREDIT_CHECKING_ACH
          - CREDIT_SAVING_ACH
          - CREDIT_TRANSFER_ACH
          - CREDIT_TRANSFER_CARD
          - CUR_CONVERSION_FEE_CARD
          - DEBIT_CHECKING_ACH
          - DEBIT_SAVING_ACH
          - DEBIT_TRANSFER_ACH
          - DISPUTE_CHARGEBACK_CARD
          - DISPUTE_PROVISIONAL_CREDIT_CARD
          - INTERCHANGE_CARD
          - MERCHANT_CREDIT_CARD
          - MICRO_DEPOSIT_ACH
          - MONEY_TRANSFER_CARD
          - OTHER_CARD
          - PAYPAL_CREDIT_ACH
          - PIN_INTERCHANGE_CARD
          - PIN_PURCHASE_CARD
          - PIN_RETURN_CARD
          - POS_VERIFICATION_CARD
          - PRE_AUTH_COMPLETION_CARD
          - PRE_AUTH_CREDIT _CHECKING_ACH
          - PRE_AUTH_CREDIT _SAVING_ACH
          - PRE_AUTH_DEBIT _CHECKING_ACH
          - PRE_AUTH_DEBIT _SAVING_ACH
          - PRE_AUTH_FORCE_CARD
          - PURCHASE_CARD
          - RDC_CHECK_ACH
          - REFUND_CARD
          - RETURN_CARD
          - RETURN_CREDIT_CHECKING_ACH
          - RETURN_CREDIT_SAVING_ACH
          - RETURN_DEBIT_CHECKING_ACH
          - RETURN_DEBIT_SAVING_ACH
          - REVERSAL_ACH
          - REVERSAL_CARD
          type: string
      title: Transaction
      type: object
    lead_mode_account:
      properties:
        id:
          description: Account ID
          format: uuid
          readOnly: true
          type: string
        account_number:
          description: Account number
          readOnly: true
          type: string
        currency:
          description: Account currency or account settlement currency. ISO 4217 alphabetic
            currency code. Default USD
          example: faker.finance.currencyCode
          type: string
        status:
          $ref: '#/components/schemas/status'
        exchange_rate_type:
          description: Exchange rate type
          example: M, INTERBANK, CUST
          type: string
        iban:
          description: International bank account number
          type: string
        swift_code:
          description: SWIFT code
          type: string
        is_account_pool:
          description: Account is investment (variable balance) account or a multi-balance
            account pool. Default false
          type: boolean
        account_template_code:
          description: Account template code
          type: string
        account_template_version:
          description: Account template version
          type: number
        relationships:
          description: List of the relationship for this account to the parties
          items:
            $ref: '#/components/schemas/schemas-relationship'
          type: array
        aliases:
          description: A list of the aliases for account. Account alias is the account
            number of different balance types to link to the same account ID
          items:
            $ref: '#/components/schemas/alias'
          type: array
          writeOnly: true
        balances:
          description: A list of balances for account based on different type
          items:
            $ref: '#/components/schemas/balance'
          readOnly: true
          type: array
        recent_transactions:
          description: The most recent 10 transactions of the account
          items:
            $ref: '#/components/schemas/transaction'
          readOnly: true
          type: array
      required:
      - relationships
      - template_code
      - template_version
      title: Account Lead Mode
      type: object
    shadow_mode_account:
      properties:
        id:
          description: Account ID
          format: uuid
          readOnly: true
          type: string
        account_number:
          description: Account number
          type: string
        currency:
          description: Account currency or account settlement currency. ISO 4217 alphabetic
            currency code. Default USD
          example: faker.finance.currencyCode
          type: string
        status:
          $ref: '#/components/schemas/status'
        is_account_pool:
          description: Account is investment (variable balance) account or a multi-balance
            account pool. Default false
          type: boolean
        relationships:
          description: List of the relationship for this account to the parties
          items:
            $ref: '#/components/schemas/schemas-relationship'
          type: array
        aliases:
          description: A list of aliases for account. Account alias is the account
            number of different balance types to link to the same account ID
          items:
            $ref: '#/components/schemas/alias'
          type: array
          writeOnly: true
        balances:
          description: A list of balances for account based on different type
          items:
            $ref: '#/components/schemas/balance'
          readOnly: true
          type: array
        recent_transactions:
          description: The most recent 10 transactions of the account
          items:
            $ref: '#/components/schemas/transaction'
          readOnly: true
          type: array
      required:
      - account_number
      - status
      title: Shadow mode account
      type: object
    account:
      description: Account
      oneOf:
      - $ref: '#/components/schemas/lead_mode_account'
      - $ref: '#/components/schemas/shadow_mode_account'
    customer:
      description: Represents a Customer's information
      example:
        creation_time: 2000-01-23T04:56:07.000+00:00
        alt_phone_number: faker.helpers.replaceSymbols(+##########)
        devices:
        - screen_width: 0
          screen_height: 6
          os: Android
          ip: faker.internet.ip
          os_version: faker.helpers.replaceSymbols(##.##.##)
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - screen_width: 0
          screen_height: 6
          os: Android
          ip: faker.internet.ip
          os_version: faker.helpers.replaceSymbols(##.##.##)
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        related_customers:
        - relationship_role: CUSTODIAN
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - relationship_role: CUSTODIAN
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        last_name: faker.name.lastName
        middle_name: faker.name.middleName
        ssn: faker.helpers.replaceSymbols(###-##-####)
        mobile_phone_number: faker.helpers.replaceSymbols(+##########)
        legal_address:
          country_code: faker.address.countryCode
          city: faker.address.city
          address_line_1: faker.address.streetAddress
          default_address_flg: true
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address_line_2: faker.address.secondaryAddress
          state: faker.address.stateAbbr
          type: work
          postal_code: faker.address.zipCode(#####)
        last_updated_time: 2000-01-23T04:56:07.000+00:00
        dob: 2000-01-23
        ssn_last_four: '***-**-6789'
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        shipping_address:
          country_code: faker.address.countryCode
          city: faker.address.city
          address_line_1: faker.address.streetAddress
          default_address_flg: true
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address_line_2: faker.address.secondaryAddress
          state: faker.address.stateAbbr
          type: work
          postal_code: faker.address.zipCode(#####)
        accounts:
        - null
        - null
        first_name: faker.name.firstName
        email: faker.internet.email
      properties:
        id:
          description: Customer unique identifier
          format: uuid
          readOnly: true
          type: string
        first_name:
          description: Customer's first name
          example: faker.name.firstName
          type: string
        last_name:
          description: Customer's last name
          example: faker.name.lastName
          type: string
        middle_name:
          description: Customer's middle name
          example: faker.name.middleName
          type: string
        legal_address:
          $ref: '#/components/schemas/address'
        shipping_address:
          $ref: '#/components/schemas/address'
        dob:
          description: Customer's date of birth in ISO-8601 date format YYYY-MM-DD
          format: date
          type: string
        ssn:
          description: Customer's full tax ID eg SSN formatted with hyphens 123-45-6789
          example: faker.helpers.replaceSymbols(###-##-####)
          pattern: ^\d{3}-\d{2}-\d{4}$
          type: string
          writeOnly: true
        ssn_last_four:
          description: Customer's masked tax ID eg SSN formatted with hyphens ***-**-6789
          example: '***-**-6789'
          pattern: ^\d{3}-\d{2}-\d{4}$
          readOnly: true
          type: string
        email:
          description: Customer's email
          example: faker.internet.email
          type: string
        mobile_phone_number:
          description: Customer's mobile phone number in E.164 format e.g. +19178675309
          example: faker.helpers.replaceSymbols(+##########)
          pattern: ^\+?[1-9]\d{1,14}$
          type: string
        alt_phone_number:
          description: Customer's alternate phone number in E.164 format e.g. +19178675309
          example: faker.helpers.replaceSymbols(+##########)
          pattern: ^\+?[1-9]\d{1,14}$
          type: string
        creation_time:
          format: date-time
          readOnly: true
          type: string
        last_updated_time:
          format: date-time
          readOnly: true
          type: string
        devices:
          description: List of the Customer's associated devices
          items:
            $ref: '#/components/schemas/device'
          type: array
        related_customers:
          description: Customer's relationships with other accounts eg. guardian
          items:
            $ref: '#/components/schemas/relationship'
          type: array
        accounts:
          description: List of accounts that belong to the customer
          items:
            $ref: '#/components/schemas/account'
          readOnly: true
          type: array
      required:
      - dob
      - email
      - first_name
      - last_name
      - legal_address
      - mobile_phone_number
      - shipping_address
      title: Customer
      type: object
    paginated_response:
      properties:
        next_page_token:
          description: If returned, use the next_page_token to query for the next
            page of results.
          example: faker.random.alphaNumeric(10)
          type: string
      title: Paginated List response
      type: object
    ProspectResponse:
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: Customer id to use for segment disclosure tracking and customer
            creation
          format: uuid
          type: string
      title: ProspectResponse
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: api_key
      scheme: bearer
      type: http
