openapi: 3.0.3
info:
  description: |
    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
  title: Synctera API
  version: 0.5.0
servers:
- description: Production
  url: https://api.synctera.com/v0
- description: Sandbox (no real world financial impact)
  url: https://api-sandbox.synctera.com/v0
security:
- bearerAuth: []
tags:
- description: Requests to create and manage webhooks
  name: Webhooks
paths:
  /webhooks:
    get:
      description: List all webhooks
      operationId: listWebhooks
      parameters:
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          description: Maximum of objects to return per page
          example: 100
          minimum: 1
          type: integer
        style: form
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          description: Optional pagination token to be provided to retrieve subsequent
            pages, returned from previous get
          example: faker.random.alphaNumeric(10)
          type: string
        style: form
      - explode: true
        in: query
        name: is_enabled_only
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    documents:
                      description: Array of webhooks
                      items:
                        $ref: '#/components/schemas/webhook'
                      type: array
                  type: object
                - $ref: '#/components/schemas/paginated_response'
          description: List of webhooks
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: List webhooks
      tags:
      - Webhooks
    post:
      description: Create a webhook
      operationId: createWebhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/webhook'
        description: Webhook to create
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook'
          description: Created webhook
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Create a webhook
      tags:
      - Webhooks
  /webhooks/{webhook_id}:
    delete:
      description: Delete a webhook
      operationId: deleteWebhook
      parameters:
      - description: Webhook ID
        explode: false
        in: path
        name: webhook_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delete_response'
          description: Resource has been deleted
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Delete a webhook
      tags:
      - Webhooks
    get:
      description: Get a webhook
      operationId: getWebhook
      parameters:
      - description: Webhook ID
        explode: false
        in: path
        name: webhook_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook'
          description: Webhook
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Get a webhook
      tags:
      - Webhooks
    put:
      description: Update a webhook
      operationId: updateWebhook
      parameters:
      - description: Webhook ID
        explode: false
        in: path
        name: webhook_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/webhook'
        description: Webhook to update
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook'
          description: Created webhook
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Update a webhook
      tags:
      - Webhooks
  /webhooks/{webhook_id}/events:
    get:
      description: List webhook events. This response will not associate with the
        event response history.
      operationId: listEvents
      parameters:
      - description: Webhook ID
        explode: false
        in: path
        name: webhook_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: Start date of the search range
        explode: true
        in: query
        name: start_date
        required: false
        schema:
          format: date
          type: string
        style: form
      - description: End date of the search range
        explode: true
        in: query
        name: end_date
        required: false
        schema:
          format: date
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          description: Maximum of objects to return per page
          example: 100
          minimum: 1
          type: integer
        style: form
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          description: Optional pagination token to be provided to retrieve subsequent
            pages, returned from previous get
          example: faker.random.alphaNumeric(10)
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    event_list:
                      description: Array of events
                      items:
                        $ref: '#/components/schemas/event'
                      type: array
                  type: object
                - $ref: '#/components/schemas/paginated_response'
          description: List of webhook events
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: List webhook events
      tags:
      - Webhooks
  /webhooks/{webhook_id}/events/{event_id}:
    get:
      description: Get webhook event by ID
      operationId: getEvent
      parameters:
      - description: Webhook ID
        explode: false
        in: path
        name: webhook_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: Webhook event ID
        explode: false
        in: path
        name: event_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: Webhook event
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Get webhook event
      tags:
      - Webhooks
  /webhooks/{webhook_id}/events/{event_id}/resend:
    post:
      description: Resend a webhook event
      operationId: resendEvent
      parameters:
      - description: Webhook ID
        explode: false
        in: path
        name: webhook_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: Webhook event ID
        explode: false
        in: path
        name: event_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: Delay the event triggering in seconds
        explode: true
        in: query
        name: delay
        required: false
        schema:
          maximum: 3600
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: Resent webhook event
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Resend an event
      tags:
      - Webhooks
  /webhooks/secret:
    delete:
      description: Revoke the existing webhook secret. If this is called at the rolling
        secret time, then both old and new secrets will be revoked
      operationId: revokeSecret
      responses:
        "200":
          description: Secret has been revoked
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Revoke the secret
      tags:
      - Webhooks
    post:
      description: Create a webhook secret. The secret will be used to verify all
        subsequent webhook request signature.
      operationId: createSecret
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
          description: Webhook secret response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource already exists error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Create a secret
      tags:
      - Webhooks
    put:
      description: Replace an existing webhook secret immediately or as part of rotation.
        This new secret will be used to verify all subsequent webhook request signature.
      operationId: replaceSecret
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                is_rolling_secret:
                  description: Set true to let the current secret expire in the next
                    24 hours. Set false to let the current secret expire immediately.
                  type: boolean
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Webhook secret response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Replace an existing secret
      tags:
      - Webhooks
  /webhooks/trigger:
    post:
      description: Trigger an specific event for webhook testing purpose
      operationId: triggerEvent
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/json:
            schema:
              properties:
                event:
                  $ref: '#/components/schemas/event_type'
              type: object
        description: Provide an event type to trigger
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: Triggered webhook event
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Trigger an event
      tags:
      - Webhooks
components:
  parameters:
    limit:
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 100
        description: Maximum of objects to return per page
        example: 100
        minimum: 1
        type: integer
      style: form
    page_token:
      explode: true
      in: query
      name: page_token
      required: false
      schema:
        description: Optional pagination token to be provided to retrieve subsequent
          pages, returned from previous get
        example: faker.random.alphaNumeric(10)
        type: string
      style: form
    webhook_id:
      description: Webhook ID
      explode: false
      in: path
      name: webhook_id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
      required: true
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  responses:
    unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unauthorized
    internal_server_error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Internal server error
    not_found:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Resource not found
    delete_response:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/delete_response'
      description: Resource has been deleted
    already_exists:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Resource already exists error
  schemas:
    event_type:
      description: The type of the webhook event. Items ends with .* means all events
        that match the prefix (major type. e.g. ACCOUNT, KYC etc). One webhook allows
        one major type only.
      enum:
      - ACCOUNT.*
      - ACCOUNT.STATUS_CHANGED
      - TRANSACTION.*
      - TRANSACTION.POSTED
      - TRANSACTION.FAILED
      - KYC.*
      - KYC.CUSTOMER_MANUAL_REVIEW
      - KYC.PASS
      - KYC.FAILED_MANUAL_REVIEW
      - KYC.FOUND_ON_WATCHLIST
      - KYC.ADDITIONAL_DOC_REQUIRED
      - LEDGER.*
      - LEDGER.BALANCE_CHANGED.ACH_REVERSALS
      - LEDGER.BALANCE_CHANGED.INTEREST
      - LEDGER.BALANCE_CHANGED.WIRES
      - LEDGER.BALANCE_CHANGED.CHECK_DEPOSIT
      - CARD.*
      - CARD.FULFILLMENT_UPDATE
      - CARD.TERMINATION
      - CARD.STATUS_CHANGE
      - RECONCILIATION.*
      - RECONCILIATION.PROCESSED
      title: All the webhook event types
      type: string
    webhook:
      description: Webhook object
      example:
        is_enabled: true
        metadata: metadata
        last_updated: 2000-01-23T04:56:07.000+00:00
        enabled_events:
        - null
        - null
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        url: https://openapi-generator.tech
      properties:
        id:
          description: The unique ID of the webhook
          format: uuid
          type: string
        url:
          description: URL that the webhook will send request to
          format: uri
          maxLength: 1000
          type: string
        description:
          description: A description of what the webhook is used for
          type: string
        enabled_events:
          description: A list of the events that will trigger the webhook
          items:
            $ref: '#/components/schemas/event_type'
          type: array
        metadata:
          description: Additional information stored to the webhook
          maxLength: 1024
          type: string
        last_updated:
          description: Timestamp that this webhook was created or the last time any
            field was changed
          format: date-time
          readOnly: true
          type: string
        is_enabled:
          description: Set the webhook to be enabled or disabled
          type: boolean
      required:
      - enabled_events
      - is_enabled
      - url
      title: Webhook
      type: object
    paginated_response:
      properties:
        next_page_token:
          description: If returned, use the next_page_token to query for the next
            page of results.
          example: faker.random.alphaNumeric(10)
          type: string
      title: Paginated List response
      type: object
    error:
      properties:
        error_details:
          description: Detailed description of error
          example: faker.lorem.sentence
          type: string
      title: Error
      type: object
    delete_response:
      description: Deleted object information
      example:
        resource: resource
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: Object ID
          format: uuid
          type: string
        resource:
          description: The resource name
          type: string
      title: Deleted Object
      type: object
    event:
      description: Webhook event object
      example:
        metadata: metadata
        response_history:
        - sent_time: 2000-01-23T04:56:07.000+00:00
          code: 0
          response_body: response_body
          response_time: 2000-01-23T04:56:07.000+00:00
        - sent_time: 2000-01-23T04:56:07.000+00:00
          code: 0
          response_body: response_body
          response_time: 2000-01-23T04:56:07.000+00:00
        webhook_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        event_resource: '{}'
        event_time: 2000-01-23T04:56:07.000+00:00
        status: RUNNING
      properties:
        id:
          description: Unique event ID of the webhook request. Use event endpoints
            to get more event summary data
          format: uuid
          readOnly: true
          type: string
        webhook_id:
          description: Webhook the current event belongs to
          format: uuid
          type: string
        type:
          $ref: '#/components/schemas/event_type'
        event_time:
          description: Timestamp of the current event raised
          format: date-time
          type: string
        metadata:
          description: Metadata that stored in the webhook subscription
          maxLength: 1024
          type: string
        event_resource:
          description: "Json string of object associated with the event. For example,\
            \ if your event is ACCOUNT.STATUS_CHANGE, You can refer to Acccount to\
            \ parse the account event to obtain the ID, status etc. \n"
          type: object
        status:
          description: Current event status. Failing event will keep retry until it
            is purged.
          enum:
          - RUNNING
          - SUCCESS
          - RETRYING
          type: string
        response_history:
          description: Response history of the webhook request
          items:
            $ref: '#/components/schemas/event_response_history'
          type: array
      title: Webhook event
      type: object
    inline_object:
      properties:
        is_rolling_secret:
          description: Set true to let the current secret expire in the next 24 hours.
            Set false to let the current secret expire immediately.
          type: boolean
      type: object
    inline_response_200:
      example:
        delete_at: 2000-01-23T04:56:07.000+00:00
        secret: secret
      properties:
        secret:
          description: Generated secret. Do not share. This secret will be used to
            verify that webhook requests were sent from Synctera.
          maxLength: 64
          minLength: 64
          type: string
        delete_at:
          description: Timestamp that the old secret is delete
          format: date-time
          type: string
      type: object
    inline_response_201:
      example:
        secret: secret
      properties:
        secret:
          description: Generated secret. Do not share. This secret will be used to
            verify that webhook requests were sent from Synctera.
          maxLength: 64
          minLength: 64
          type: string
      type: object
    inline_object_1:
      properties:
        event:
          $ref: '#/components/schemas/event_type'
      type: object
    event_response_history:
      example:
        sent_time: 2000-01-23T04:56:07.000+00:00
        code: 0
        response_body: response_body
        response_time: 2000-01-23T04:56:07.000+00:00
      properties:
        code:
          description: Response code from the request
          type: integer
        response_body:
          description: Response body from the request
          type: string
        sent_time:
          description: Timestamp that the request is sent
          format: date-time
          type: string
        response_time:
          description: Timestamp that the response is received
          format: date-time
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: api_key
      scheme: bearer
      type: http
